add re nota
FutureBaseEditor/PiyanoApp pull request #2
Opened 2023-04-01 10:57 UTC by okantirpanci

2023-04-01 10:57 UTC, FutureBaseEditor approved these changes

2023-04-02 07:12 UTC, mfdsoftdev requested changes
the tone of the note hasn't been fully met, can you change it please?

2023-04-02 07:15 UTC, mfdsoftdev submitted a review, later dismissed

2023-04-02 07:49 UTC, RecepPekdas approved these changes

2023-04-02 07:50 UTC, FutureBaseEditor requested changes

2023-04-02 07:50 UTC, FutureBaseEditor commented on Program.cs
> +            int re = 293;
Bu kod olmamaış!!!!

2023-04-02 07:52 UTC, FutureBaseEditor commented on Program.cs
> +            int re = 293;
akassasa

2023-04-02 07:59 UTC, RecepPekdas approved these changes

2023-04-02 07:59 UTC, ZeynepColakoglu approved these changes

2023-04-02 07:59 UTC, AlperVatansever submitted a review, later dismissed

2023-04-02 07:59 UTC, gultan7 submitted a review, later dismissed

2023-04-02 07:59 UTC, Ali1988Baba submitted a review, later dismissed

2023-04-02 08:14 UTC, Ali1988Baba submitted a review, later dismissed
it's good

2023-04-02 08:14 UTC, mfdsoftdev submitted a review, later dismissed

2023-04-02 08:15 UTC, AlperVatansever approved these changes

2023-04-02 08:15 UTC, Ali1988Baba approved these changes
okk

2023-04-02 08:16 UTC, merged